### PR TITLE
[#120] Support aliases in tl visit.

### LINKED ISSUE #120: Support aliases in tl visit
Currently aliases aren't supported in the `tl visit` command.

```
tl visit myalias


  [InvalidArgumentException]
  No such ticket was found in any backends.
```

### PR DESCRIPTION
**Pull request by jibran**
Fixes #120

### CODE REVIEW

**Review by larowlan — APPROVED** [review]

File: src/Commands/Visit.php [hunk 1]
```diff
@@ -84,7 +87,7 @@ protected function open($url, OutputInterface $output) {
       $browser = 'start';
     }
 
-    if ($browser) {
+    if ($browser && !isset($GLOBALS['__PHPUNIT_BOOTSTRAP'])) {
```
Comment (jibran) [inline src/Commands/Visit.php:90]: This is kind of ugly. Do we have a better way to do this?

Comment (larowlan) [reply src/Commands/Visit.php:90]: you could put a constant in phpunit.xml and then use `!defined()`

Comment (jibran) [reply src/Commands/Visit.php:90]: That's almost the same thing :D. I tested it locally it works. We can improve it later.
